### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by ygongdev** [elwayman02/ember-resize-modifier#328]
[There is a long ongoing discussion on this error, which can be safely ignored](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded).

But since this error can happen and break tests, should we capture and ignore this error in this library to avoid having the consumers doing it themselves?

**Comment by elwayman02** [comment]
Maybe this is something that could be solved internally by https://github.com/PrecisionNutrition/ember-resize-observer-service if we resolve #247?

**Comment by chbonser** [comment]
@elwayman02 I like your thoughts in #247 then having this issues addressed in that library. In the interim I created a PR that seems to work in our use case. I don't know if it is the right answer in all situations though...

**Comment by elwayman02** [comment]
I think the best approach, if we "fix" this at all, is to simply catch the error and ignore it.

**Comment by elwayman02** [comment]
Fixed by #506
