### ISSUE TITLE
Released package size is 74MB

### ISSUE THREAD

**Issue by cddso** [elwayman02/ember-resize-modifier#784]
The released package of 0.6.0 is 74MB. There is a huge `.yarn` file present in the released package (also an `.idea` file). This was not the case in version 0.4.1 when the package size was only 30kB. I'm assuming something changed in release strategy causing these unwanted files to end up in the released package.

**Comment by elwayman02** [comment]
This was fixed in #761, but there hasn't been a new release since. The next release will reduce the size again, sorry!

**Comment by SergeAstapov** [comment]
@elwayman02 @cddso as v0.7.1 was out seem like this can be closed?
